### ISSUE TITLE
Fix the localhost:8545 error in dashboard.

### ISSUE THREAD

**Issue by kamikazebr** [1Hive/celeste-dashboard#154]
In https://celeste.1hive.org/#/dashboard

It try connect to localhost

![image](https://user-images.githubusercontent.com/691510/153067989-b14f1d31-2e41-45d8-a7e0-c0bb9057be76.png)

**Comment by kamikazebr** [comment]
![image](https://user-images.githubusercontent.com/691510/153073133-8e997398-4f60-4b1f-bc5d-5da7b886a57c.png)

It's looking the errors ocurrs here, just need some futher investigation to know the cause

**Comment by 0xGabi** [comment]
I believe it might be related to these lines: https://github.com/1Hive/celeste-dashboard/blob/master/src/lib/web3-utils.js#L27-L32

```
export function getDefaultProvider(chainId = getPreferredChain()) {
  const type = getNetworkType(chainId)
  const defaultEthNode = getDefaultEthNode(chainId)

  return defaultEthNode
    ? new Providers.StaticJsonRpcProvider(defaultEthNode)
    : ethers.getDefaultProvider(type, getBackendServicesKeys())
}
```

In particular, every time we are using `getDefaultProvider` we have to double-check if we are providing the right `chainId`. Let's review the `getPreferredChain`, `getNetworkType`, and `getDefaultEthNode` are working fine.

**Comment by 0xGabi** [comment]
Also, @fabriziovigevani might have a better understanding here.

**Comment by kamikazebr** [comment]
> I believe it might be related to these lines: https://github.com/1Hive/celeste-dashboard/blob/master/src/lib/web3-utils.js#L27-L32
> 
> ```
> export function getDefaultProvider(chainId = getPreferredChain()) {
>   const type = getNetworkType(chainId)
>   const defaultEthNode = getDefaultEthNode(chainId)
> 
>   return defaultEthNode
>     ? new Providers.StaticJsonRpcProvider(defaultEthNode)
>     : ethers.getDefaultProvider(type, getBackendServicesKeys())
> }
> ```
> 
> In particular, every time we are using `getDefaultProvider` we have to double-check if we are providing the right `chainId`. Let's review the `getPreferredChain`, `getNetworkType`, and `getDefaultEthNode` are working fine.

Yes. I got to them. I think good way its write small unit test to ensure it works properly.

**Comment by kamikazebr** [comment]
![image](https://user-images.githubusercontent.com/691510/155814681-01a31e15-89c4-4b36-810e-de504fa1615d.png)
I made some unit tests.

now i'll investigate why it getting `null`

@0xGabi

**Comment by kamikazebr** [comment]
The `getDefaultProvider` only return the default chain ID when it its called `without args`, like `undefined`

![image](https://user-images.githubusercontent.com/691510/155820103-0da7fc65-c95c-47b1-88fb-edbab034a5f5.png)

When passed `NULL`, so it point to `localhost`

**Comment by kamikazebr** [comment]
The PR need be reviewed https://github.com/1Hive/celeste-dashboard/pull/155
