### ISSUE TITLE
Connecting email bug

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/celeste-dashboard#41]
**Which is the issue**
When I connect my address it asks me to sign up to email notifications, I say "no thanks" but then it brings up a signature request and whether I sign it or I cancel it, it gives me a different fail message.

**How is expected for you to work**
I would expect that if I say "No Thanks" that there wouldn't be a signature request prompt. 

**If is an UI issue please attach a screenshot**

After selecting "No Thanks"
![Screen Shot 2021-03-04 at 2 02 06 AM](https://user-images.githubusercontent.com/25679386/109924979-1b974c80-7c8f-11eb-93ae-1292d9fc7c8c.png)

If I cancel the signature request
![Screen Shot 2021-03-04 at 2 02 16 AM](https://user-images.githubusercontent.com/25679386/109924978-1afeb600-7c8f-11eb-8496-c7b035080e77.png)

If I accept the signature request (I did not give email at all)
![Screen Shot 2021-03-04 at 2 02 29 AM](https://user-images.githubusercontent.com/25679386/109924977-1a661f80-7c8f-11eb-8b3d-86431194cb53.png)

**Steps on how to reproduce the issue**
You can reproduce this by simply disconnecting and reconnecting a wallet.

**Comment by jessicazartler** [comment]
Seconding this bug

<img width="954" alt="Cannot connect to notifications" src="https://user-images.githubusercontent.com/43972522/110147621-e92e4200-7da9-11eb-8d85-0c104885b40d.png">

**Comment by KZFlyer** [comment]
I also received this when entering a valid email address and signing.
![image](https://user-images.githubusercontent.com/39107717/110230081-6528a700-7edc-11eb-844c-cc78f7ef059b.png)

**Comment by fabriziovigevani** [comment]
Thank you guys for the report!
The notifications service is now up.

Please try authenticating through https://celeste-rinkeby.1hive.org/#/
