### ISSUE TITLE
Can't submit "Execute Ruling" 

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/celeste-dashboard#44]
**Which is the issue**
I have an "Allowed Action" on question #3 but when I click the button 'Execute Ruling" the transaction fails. I tried twice with 1 gwei, then tried once at 2 gwei

**How is expected for you to work**
I would expect that the transaction would go through and that my 0.1 HNY stake would be returned

If is an UI issue please attach a screenshot
![Screen Shot 2021-03-04 at 3 28 15 AM](https://user-images.githubusercontent.com/25679386/109934188-3d4a0100-7c9a-11eb-96b0-4578a51df002.png)
![Screen Shot 2021-03-04 at 3 27 52 AM](https://user-images.githubusercontent.com/25679386/109934191-3de29780-7c9a-11eb-925a-05ac73ab73ed.png)

Steps on how to reproduce the issue
I staked 0.1 HNY on an outcome for a questions. I was assigned as a Keeper and I voted in favour of what I had picked previously to be the outcome. The time elapsed and the question was resolved. The "Execute Ruling" button appeared, but every time I click it and confirm the transaction it fails.

**Comment by CurlyBracketEffect** [comment]
I tried again after another term timer expired and the transaction went through.

I then experienced the error explained in #45 and now when I reload the page and try to connect my wallet again I get another Unexpected Error:

division by zero (fault="division by zero", operation="div", code=NUMERIC_FAULT, version=bignumber/5.0.6)
in Wy
in Rg
in Dg
in Ky
in t
in t
in ES
in nr
in bb
in div
in t
in Layout___StyledDiv
in _
in div
in t
in MainView___StyledDiv6
in div
in t
in MainView___StyledDiv5
in div
in t
in ScrollView___StyledDiv
in l
in div
in l
in t
in MainView___StyledRootProvider
in div
in t
in MainView___StyledDiv3
in div
in t
in MainView___StyledDiv
in tf
in Fe
in ot
in er
in n
in t
in n
in _
in n
in n
in div
in l
in N
in Provider
in Unknown
in Pe
in t
in t
in je
in sr
in Unknown
in ur
in we
in OS
in Unknown

**Comment by fabriziovigevani** [comment]
closed by https://github.com/1Hive/celeste-subgraph/pull/6

Phase terms were off, causing inconsistent phase term durations.

Thanks for reporting @CurlyBracketEffect !
