### ISSUE TITLE
An unexpected error

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/celeste-dashboard#45]
**Which is the issue**
I  submitted an "Execute Ruling" transaction for the 4th time as discussed in mentioned #44, and it finally went through. I clicked on the Dashboard link in the side panel to see if my stake had been freed up, and I got an Unexpected Error. I clicked report and it didn't seem to do anything, so I decided to report it here.

Here is the text from the more details box: 

division by zero (fault="division by zero", operation="div", code=NUMERIC_FAULT, version=bignumber/5.0.6)
in Wy
in Rg
in Dg
in Ky
in t
in t
in ES
in nr
in bb
in div
in t
in Layout___StyledDiv
in _
in div
in t
in MainView___StyledDiv6
in div
in t
in MainView___StyledDiv5
in div
in t
in ScrollView___StyledDiv
in l
in div
in l
in t
in MainView___StyledRootProvider
in div
in t
in MainView___StyledDiv3
in div
in t
in MainView___StyledDiv
in tf
in Fe
in ot
in er
in n
in t
in n
in _
in n
in n
in div
in l
in N
in Provider
in Unknown
in Pe
in t
in t
in je
in sr
in Unknown
in ur
in we
in OS
in Unknown
 
**How is expected for you to work**
I would expect that I would have been taken back to the dashboard and that when I clicked the "Report" on the Unexpected Error page that it would send a report and inform me that the report was sent. 

**If is an UI issue please attach a screenshot**

![Screen Shot 2021-03-04 at 3 36 14 AM](https://user-images.githubusercontent.com/25679386/109935623-c7469980-7c9b-11eb-9e9b-d0c2de8049e8.png)

**Steps on how to reproduce the issue**
See previous description and issue

**Comment by CurlyBracketEffect** [comment]
I have completely cleared my cache for the site and hard reloaded it. When I reloaded the page it gave me the 4 slide welcome message again, but again when I try to connect my wallet I get the "Unexpected Error". It seems like the site specifically doesn't like my address because I am able to connect a different address, but it doesn't have any test HNY. I suppose I could send my test HNY and ETH to that account and continue testing....but this definitely seems like something that needs solving.

**Comment by fabriziovigevani** [comment]
This is closed by #49
