### ISSUE TITLE
Open Unknown to sign the Transaction - scary for updating the Term

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/celeste-dashboard#56]
<img width="423" alt="Screen Shot 2021-03-07 at 9 16 36 AM" src="https://user-images.githubusercontent.com/14945613/110242865-3a7c3400-7f58-11eb-8269-6ef687f28961.png">

**Comment by fabriziovigevani** [comment]
The issue was already reported and a fix was merged today!

https://github.com/1Hive/celeste-dashboard/pull/52
