### ISSUE TITLE
Issues with flow

### ISSUE THREAD

**Issue by willjgriff** [1Hive/celeste-dashboard#73]
When attempting to execute a ruling after a dispute had finalised (according the UI) the execute function reverted. However, after one term the execute function executed successfully. Can we check whether the execute function is being displayed at the correct time?

Also there isn't any opportunity to execute "settle" through the UI. Should there be a chance to execute settle (similar to how draft can be executed) or do we just have to wait for the service to execute it?

**Comment by fabriziovigevani** [comment]
Issue was fixed at https://github.com/1Hive/celeste-dashboard/pull/80

Regarding showing a button to settle dispute' rounds. Yeah i think that makes sense. I recall having that as a nice to have feature for Aragon Court and it never was  implemented but i think that could be useful and also give the chance to users to earn some HNY fees.

**Comment by willjgriff** [comment]
Fair, well if you feel you've got time once everything else is sorted perhaps look into it. Might be a bit involved though because I there's different settle functions to call depending on the state of the dispute.

**Comment by fabriziovigevani** [comment]
Ah yeah, though from the dispute detail view we would only be settling penalties because the reward and appeal settlement is done through the rewards module by each juror that claims rewards (if the service didn't already).

**Comment by fabriziovigevani** [comment]
Will close this issue and create a new one with the penalty settlement feature
