### ISSUE TITLE
HNY amount only displaying to 1 decimal place

### ISSUE THREAD

**Issue by CurlyBracketEffect** [1Hive/celeste-dashboard#77]
At some point, I had gotten some rewards that showed up on my Dashboard, but the rewards were less than 0.1 HNY and so the amount only displayed a '0'

![Screen Shot 2021-03-12 at 2 52 43 PM](https://user-images.githubusercontent.com/25679386/110996942-adb3ea80-834a-11eb-9b63-3a3cd996c38f.png)

I also noticed that all prices for HNY are displayed to only 1 decimal place. As the HNY value increases and more new members join the DAO I feel like it will become a more common case that people will have smaller fractions of HNY and so I would expect that the interface would show more decimal places when displaying HNY amounts. 

As a side note, this made me think about what the smallest denomination of HNY is called; for Bitcoin we have satoshi and for ETH we have gwei...what is it for HNY? Perhaps when a HNY amount is smaller than a few decimal places we could display it as a whole number of a new unit name.

**Comment by fabriziovigevani** [comment]
Yeah that's a fair point! I updated all the HNY amounts to be displayed with 3 decimal places.

> As a side note, this made me think about what the smallest denomination of HNY is called; for Bitcoin we have satoshi and for ETH we have gwei...what is it for HNY? Perhaps when a HNY amount is smaller than a few decimal places we could display it as a whole number of a new unit name.

Haha that's a good question! Will give it a think, maybe we could also open up a forum post and see what ideas the community could  come  up with 😄

**Comment by fabriziovigevani** [comment]
closed by #85

**Comment by CurlyBracketEffect** [comment]
I did end up starting a forum post about this:
@fabriziovigevani 
https://forum.1hive.org/t/what-is-the-smallest-unit-of-honey-called/2957?u=curlybracketeffect
