### ISSUE TITLE
Can't activate more but no reason why.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/celeste-dashboard#87]
This screen should show an info box with the max I can activate. In my case I know it's 0 because I've already activated the max but there's no explanation for why I can't activate more. The message could read "Each keeper is restricted to staking a maximum amount determined by the total amount staked to Celeste. The higher the total amount staked the less individual keepers can stake. The max you can currently stake is 0 HNY."
<img width="473" alt="Screenshot 2021-03-16 at 16 32 33" src="https://user-images.githubusercontent.com/9317743/111345608-5f1d8d80-8675-11eb-901e-e4c3b442adda.png">

Also can remove the space in the top action text.
<img width="471" alt="Screenshot 2021-03-16 at 16 38 27" src="https://user-images.githubusercontent.com/9317743/111346348-0ac6dd80-8676-11eb-9e38-ffa715e0f19e.png">

**Comment by fabriziovigevani** [comment]
I would change `stake` for `activate` since we don't really use Staking terminology here.
