### ISSUE TITLE
Rewards box layout and text.

### ISSUE THREAD

**Issue by willjgriff** [1Hive/celeste-dashboard#95]
How do we feel about using the "rewards" instead of "fees" here and have "Ruling rewards" and "Dispute rewards"? Also could "Ruling rewards" have a tooltip which says "These rewards are from keepers who failed to vote with the majority ruling."

Also renaming "Subscriptioons" to "Staking rewards" as suggested by @lkngtn and perhaps swapping "Staking rewards" with "Dispute rewards" as Ruling and Dispute rewards are more closely related? 

Dispute rewards could also have a tooltip saying "These rewards are for voting in disputes that you have been drafted in."

For Staking rewards can we put the timer inside the warning maybe and remove the tool tip, not the prettiest but I think better than having the tooltip. The text could be: "You must claim your staking rewards within "timer" or you will forfeit them."

Also full stop at the end of the Ruling rewards info box.

<img width="271" alt="Screenshot 2021-03-18 at 09 50 56" src="https://user-images.githubusercontent.com/9317743/111606773-84beaa00-87cf-11eb-922a-66652021ef99.png">

**Comment by fabriziovigevani** [comment]
Also try to remove the Ruling fees section if they have already been sent out to the inactive wallet.

**Comment by fabriziovigevani** [comment]
Here's a preview of how it would look like

![Screen Shot 2021-03-18 at 17 50 16](https://user-images.githubusercontent.com/22663232/111695955-6cbc4a00-8812-11eb-9bd0-707d8bea64a8.png)

**Comment by fabriziovigevani** [comment]
> Also could "Ruling rewards" have a tooltip which says "These rewards are from keepers who failed to vote with the majority ruling."

@fioreb Where do you think the tooltip would fit best?

**Comment by fioreb** [comment]
We can place the help button next to the Ruling Rewards title and show the tooltip there.

Also I think is better to have the timer in the warning, maybe can we have it with the same color and in bold font? Like this:

![Frame 2](https://user-images.githubusercontent.com/61423083/111704812-7f3c8080-881e-11eb-848d-431d3adb50f2.png)

**Comment by fabriziovigevani** [comment]
Ah yes! Much better 😄
